[IMP] cfg: update autofix hook versions
Vauxoo/pre-commit-vauxoo pull request #129
Opened 2023-11-27 17:34 UTC by antonag32

Autofix hooks have been updated to their latest version. Biggest change involves black removing whitespaces after class/method declarations.

BREAKING CHANGE: black may generate diffs on projects

2024-01-03 03:18 UTC, antonag32 commented
It seems like there is a problem with tmpdir generation on windows. It generates them under a different user. This stack overflow seems related:

https://stackoverflow.com/questions/51129686/gettemppatha-returning-incorrect-user-folder

2024-01-03 03:33 UTC, antonag32 commented
This hack confirms it:

```diff
diff --git a/tests/test_pre_commit_vauxoo.py b/tests/test_pre_commit_vauxoo.py
index e284313..060d1b2 100644
--- a/tests/test_pre_commit_vauxoo.py
+++ b/tests/test_pre_commit_vauxoo.py
@@ -2,6 +2,7 @@ from __future__ import annotations
 
 import logging
 import os
+import platform
 import posixpath
 import re
 import shutil
@@ -27,6 +28,11 @@ class TestPreCommitVauxoo(unittest.TestCase):
         self.old_environ = os.environ.copy()
         self.original_work_dir = os.getcwd()
         self.tmp_dir = tempfile.mkdtemp(suffix="_pre_commit_vauxoo")
+        if platform.system() == "Windows":
+            print("TMP DIR BEFORE HACK %s" % self.tmp_dir)
+            self.tmp_dir = self.tmp_dir.replace("RUNNER~1", "runneradmin")
+            print("TMP DIR AFTER HACK %s" % self.tmp_dir)
+
         os.chdir(self.tmp_dir)
         self.runner = CliRunner()
         src_path = os.path.join(os.path.dirname(os.path.dirname(os.path.realpath(__file__))), "resources")
```

2024-01-03 03:36 UTC, antonag32 commented
Marked as draft until non-hacky fix is found.

2024-01-20 20:22 UTC, luisg123v requested changes

2024-01-20 20:22 UTC, luisg123v commented on tests/test_pre_commit_vauxoo.py
> +        self.tmp_dir = os.path.realpath(tempfile.mkdtemp(suffix="_pre_commit_vauxoo"))
Could you perform this on a separate commit, please?

Because it's not strictly related and to explain in commit message why it's necessary.

2024-01-22 21:38 UTC, merged