[REF] pylint.conf: Update partner name as required author
Vauxoo/pre-commit-vauxoo pull request #99
Opened 2023-01-14 14:53 UTC by alan196

2023-01-14 14:53 UTC, alan196 commented
@luistorresm @moylop260 

Could you help me to review this PR 🙏

2023-01-14 19:46 UTC, luisg123v requested changes
Could you provide a commit description explaining why the change, please?

2023-01-23 20:26 UTC, alan196 commented
@luisg123v I updated the commit message and rebased, could you help me to review this PR 🙏

2023-01-23 20:44 UTC, luisg123v approved these changes
LGTM :+1: 

Only missing copying description to PR, but I did it by you.

2023-01-23 20:45 UTC, merged